#!/usr/bin/env sh
#xProfile Profile file run on login
xcompmgr -c &
xset dpms 30 600 1200 &
XSECURELOCK_SAVER="$HOME/.local/bin/lock-saver" xss-lock -- xsecurelock &
dbus-launch &
setxkbmap frqw &
#numlocks &
dunst &
udiskie &
screenCount=$(xrandr --query | grep " connected" | awk '{print $1}' | wc -l)
if [ "$screenCount" -eq 3 ]; then
  screenConfig --pos left
elif [ "$screenCount" -eq 2 ]; then
  screenConfig --pos top
else
  screenConfig
fi
