#!/usr/bin/env sh
#xProfile Profile file run on login
xcompmgr -c &
xset s 25 25 &
xset dpms 30 600 1200 &
xss-lock -- "$HOME/.local/bin/lockscreen" &
dbus-launch &
setxkbmap frqw &
#numlocks &
dunst &
udiskie &
screenCount=$(xrandr --query | grep " connected" | awk '{print $1}' | wc -l)
if [ "$screenCount" -eq 3 ]; then
  screenConfig --pos left
elif [ "$screenCount" -eq 2 ]; then
  screenConfig --pos top
else
  screenConfig
fi
