#!/usr/bin/env sh
#xProfile Profile file run on login
picom &
xset s 25 25 &
xset dpms 30 600 1200 &
xss-lock -- "$HOME/.local/bin/lockscreen" &
dbus-launch &
setxkbmap frqw &
#numlocks &
dunst &
udiskie &

# Ouvrir le coffre Bitwarden une fois par session. mbsync en a besoin a chaque
# synchro, et pinentry ne peut pas s'ouvrir depuis le timer systemd, qui n'a pas
# de DISPLAY : sans ce deverrouillage, la synchro s'arrete des que le coffre se
# reverrouille, et le courrier cesse d'arriver en silence.
#
# Le delai laisse dusk demarrer : xprofile s'execute avant le gestionnaire de
# fenetres, et une boite de dialogue lancee sans lui serait ingerable.
( sleep 4; rbw unlock ) &
screenCount=$(xrandr --query | grep " connected" | awk '{print $1}' | wc -l)
if [ "$screenCount" -eq 3 ]; then
  screenConfig --pos left
elif [ "$screenCount" -eq 2 ]; then
  screenConfig --pos top
else
  screenConfig
fi
