
export  ZSH_THEME_GIT_PROMPT_PREFI="["
export  ZSH_THEME_GIT_PROMPT_SUFFIX="]"
export  ZSH_THEME_GIT_PROMPT_HASH_PREFIX=":"
export  ZSH_THEME_GIT_PROMPT_SEPARATOR="|"
#export  ZSH_THEME_GIT_PROMPT_BRANCH="%{$fg_bold['022']%}%{ %G%}"
export  ZSH_THEME_GIT_PROMPT_STAGED="%{$fg[red]%}%{●%G%}"
export  ZSH_THEME_GIT_PROMPT_CONFLICTS="%{$fg[red]%}%{✖%G%}"
export  ZSH_THEME_GIT_PROMPT_CHANGED="%{$fg[blue]%}%{✚%G%}"
export  ZSH_THEME_GIT_PROMPT_BEHIND="%{↓%2G%}"
export  ZSH_THEME_GIT_PROMPT_AHEAD="%{↑%2G%}"
export  ZSH_THEME_GIT_PROMPT_STASHED="%{$fg_bold[blue]%}%{⚑%G%}"
export  ZSH_THEME_GIT_PROMPT_UNTRACKED="%{$fg[cyan]%}%{…%G%}"
export  ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg_bold[green]%}%{✔%G%}"
export  ZSH_THEME_GIT_PROMPT_LOCAL=" L"
# The remote branch will be shown between these two
export  ZSH_THEME_GIT_PROMPT_UPSTREAM_FRONT=" {%{$fg_bold[blue]%}"
export  ZSH_THEME_GIT_PROMPT_UPSTREAM_END="%{${reset_color}%}}"
