#!/usr/bin/env sh
command -v nvim >/dev/null && alias vim="nvim" vi="nvim" v="nvim" vimdiff="nvim -d" vdiff="nvim -d"
command -v make >/dev/null && alias m="make"

alias mnv='NVIM_APPNAME=neovimanu nvim' nvm='NVIM_APPNAME=neovimanu nvim'

alias mu='mirror && update'
alias u='sudo pacman -Syu'
alias ua='yay -Sua'
alias orf='yay -Rns $(yay -Qdqtt)'
alias ls='exa --icons'
alias ll='exa -lg --icons'
alias la='exa -lag --icons'
alias lt=''
treelevel() { tree -C --filesfirst -L "$@"; }
treelevelh() { tree -aC --filesfirst -L "$@"; }
treedirlevel() { tree -d -L "$@"; }
treedirlevelh() { tree -ad -L "$@"; }
alias c='composer'
alias gdoc='cd /hdd/Documents/'
alias gdw='cd /hdd/Downloads/'
alias gdv='cd /development'
alias gh="cd ${HOME}"
alias bic='bin/console'
alias df='dfc'
alias sn='shutdown now'
alias rn='sudo reboot now'
alias al='cat ${HOME}/dotfiles/shell/.config/shell/aliasesrc'
mkcd() { mkdir -p "$@" && cd "$_"; }
gpj() { cd /development/Projects/"$@"; }
mkpj() { cd /development/Projects/ && mkcd "$@"; }
gdd() { cd /hdd/"$@"; }
gdo() { cd ${$HOME}/dotfiles/"$@"; }
gpl() { [[ $1 ]] && cd ${HOME}/Projects/"$1" || cd ${HOME}/Projects/lama }
gi() { cd ${HOME}/Images/"$@"; }
gv() { cd /hdd/videos/"$@"; }
gsk() { cd /hdd/mysuckless/"$@"; }
osk() { nvim /hdd/mysuckless/"$@"; }
gc() { cd ${HOME}/.config/"$@"; }
gdc() { cd ${HOME}/dotfiles/"$@"/.config/"$@"; }
od() { nvim "${HOME}"/dotfiles/; }
gdb() { cd ${HOME}/dotfiles/bin/.local/bin; }

cd../() { cd ../"$@"; }
alias r='ranger'
alias lf='lfrun'
alias sr='sudo ranger'
alias mbsp='man bspc'
alias rt='connectTheia.sh'
ga() { git add "$@" }

