#!/usr/bin/env sh
command -v nvim >/dev/null && alias vim="nvim" vi="nvim" v="nvim" vimdiff="nvim -d"
command -v make >/dev/null && alias m="make"

alias mu='mirror && update'
alias u='sudo pacman -Syu'
alias ua='yay -Sua'
alias orf='yay -Rns $(yay -Qdqtt)'
alias ls='exa --icons'
alias ll='exa -lg --icons'
alias la='exa -lag --icons'
alias lt=''
ltl() { tree -C -L "$@"; }
ltd() { tree -d -L "$@"; }
alias c='composer'
alias gdc='cd /hdd/Documents/'
alias gdw='cd /hdd/Downloads/'
alias gdv='cd /development'
alias gh='cd ~'
alias bic='bin/console'
alias df='dfc'
alias sn='shutdown now'
alias rn='sudo reboot now'
alias al='cat ${HOME}/dotfiles/shell/.config/shell/aliasesrc'
mkcd() { mkdir -p "$@" && cd "$_"; }
gpj() { cd /development/Projects/"$@"; }
gt() { cd /development/theia/"$@"; }
mkpj() { cd /development/Projects/ && mkcd "$@"; }
gdd() { cd /hdd/"$@"; }
gi() { cd /hdd/Images/"$@"; }
gv() { cd /hdd/videos/"$@"; }
gsk() { cd /hdd/mysuckless/"$@"; }
gc() { cd ${HOME}/dotfiles/"$@"/.config/"$@"; }
gb() { cd ${HOME}/.local/bin/"$@"; }
cd../() { cd ../"$@"; }
alias dc='docker-compose up -d'
alias r='ranger'
alias lf='lfrun'
alias sr='sudo ranger'
alias ei3='nvim ~/.config/i3/config'
alias ebs='nvim ~/.config/bspwm/bspwmrc'
alias esx='nvim ~/.config/sxhkd/sxhkdrc'
alias ep='nvim ~/.config/polybar/config'
alias ev='nvim ~/.config/nvim/init.lua'
alias elf='nvim ~/.config/lf/lfrc'
alias ez='nvim ~/.config/zsh/.zshrc'
alias esh='nvim ~/.config/shell/aliasesrc'
alias exr='nvim ~/.config/Xresources'
alias exi='nvim ~/.xinitrc'
alias exp='nvim ~/.xprofile'
alias ed='nvim ~/.config/dunst/dunstrc'
alias mbsp='man bspc'
alias rt='connectTheia.sh'
