#!/usr/bin/env sh
command -v nvim >/dev/null && alias vim="nvim" vi="nvim" v="nvim" vimdiff="nvim -d"
command -v make >/dev/null && alias m="make"

alias mu='mirror && update'
alias u='sudo pacman -Syu'
alias ua='pikaur -Sua'
alias orf='pikaur -Rns $(pikaur -Qdqtt)'
alias ls='exa --icons'
alias ll='exa -lg --icons'
alias la='exa -lag --icons'
alias lt=''
ltl() { tree -C -L "$@"; }
ltd() { tree -d -L "$@"; }
alias c='composer'
alias doc='cd /hdd/Documents/'
alias dw='cd /hdd/Downloads/'
alias dev='cd /development'
alias h='cd ~'
alias bic='bin/console'
alias df='dfc'
alias sn='shutdown now'
alias rn='sudo reboot now'
mkcd() { mkdir -p "$@" && cd "$_"; }
cdpj() { cd /development/Projects/"$@"; }
hdd() { cd /hdd/"$@"; }
cdi() { cd /hdd/Images/"$@"; }
cdv() { cd /hdd/videos/"$@"; }
msk() { cd /hdd/mysuckless/"$@"; }
cdc() { cd ~/.config/"$@"; }
cds() { cd ~/.local/bin/"$@"; }
alias pl='cd /hdd/playlist/ && rm ./*.m3u && unzip ./s_iptv.zip && unzip ./fr_iptv.zip'
alias dc='docker-compose up -d'
alias r='ranger'
alias sr='sudo ranger'
alias vi3='nvim ~/.config/i3/config'
alias vbs='nvim ~/.config/bspwm/bspwmrc'
alias vsx='nvim ~/.config/sxhkd/sxhkdrc'
alias vp='nvim ~/.config/polybar/config'
alias vv='nvim ~/.config/nvim/init.vim'
alias vlf='nvim ~/.config/lf/lfrc'
alias vz='nvim ~/.config/zsh/.zshrc'
alias mbsp='man bspc'
alias vsh='nvim ~/.config/shortcutsrc'
alias vxr='nvim ~/.config/Xresources'
alias vxi='nvim ~/.xinitrc'
alias vxp='nvim ~/.xprofile'
alias vd='nvim ~/.config/dunst/dunstrc'
alias rt='connectTheia.sh'
